# Generated by Django 4.2.18 on 2025-04-01 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Voter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.TextField()),
                ('last_name', models.TextField()),
                ('street_num', models.CharField(max_length=300)),
                ('street_name', models.CharField(max_length=300)),
                ('apt_num', models.CharField(max_length=300)),
                ('zip_code', models.CharField(max_length=300)),
                ('dob', models.DateField()),
                ('reg_date', models.DateField()),
                ('party', models.CharField(max_length=5)),
                ('precint_num', models.IntegerField(null=True)),
                ('v20state', models.BooleanField(default=False)),
                ('v21town', models.BooleanField(default=False)),
                ('v21primary', models.BooleanField(default=False)),
                ('v22general', models.BooleanField(default=False)),
                ('v23town', models.BooleanField(default=False)),
                ('voter_score', models.IntegerField()),
            ],
        ),
    ]
