# Generated by Django 4.2.18 on 2025-04-02 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voter_analytics', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='voter',
            old_name='precint_num',
            new_name='precinct_num',
        ),
        migrations.AlterField(
            model_name='voter',
            name='apt_num',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='voter',
            name='first_name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='voter',
            name='last_name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='voter',
            name='party',
            field=models.CharField(max_length=2),
        ),
        migrations.AlterField(
            model_name='voter',
            name='street_name',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='voter',
            name='street_num',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='voter',
            name='zip_code',
            field=models.CharField(max_length=10),
        ),
    ]
