# Generated by Django 4.2.18 on 2025-04-02 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voter_analytics', '0002_rename_precint_num_voter_precinct_num_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='voter',
            name='precinct_num',
            field=models.CharField(max_length=5),
        ),
    ]
