# Generated by Django 4.2.18 on 2025-04-10 15:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Competition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('date', models.DateField()),
                ('location', models.CharField(max_length=100)),
                ('results', models.JSONField()),
            ],
        ),
        migrations.CreateModel(
            name='Program',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('jump_list', models.JSONField()),
                ('spin_list', models.JSONField()),
                ('GOE_list', models.JSONField()),
                ('total_score', models.FloatField()),
                ('duration', models.FloatField()),
                ('preset', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='Skater',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('nationality', models.CharField(max_length=50)),
                ('birth_date', models.DateField()),
                ('specialty', models.CharField(choices=[('jumps', 'Jumps'), ('spins', 'Spins'), ('both', 'Both')], max_length=50)),
                ('image', models.ImageField(blank=True, null=True, upload_to='skater_images/')),
                ('jump_probabilities', models.JSONField()),
                ('GOE_scores', models.JSONField()),
                ('current_program', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='current_program', to='figure_skating_game.program')),
                ('past_programs', models.ManyToManyField(related_name='past_programs', to='figure_skating_game.program')),
            ],
        ),
        migrations.AddField(
            model_name='program',
            name='skater',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='figure_skating_game.skater'),
        ),
        migrations.CreateModel(
            name='JudgingPanel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('technical_score', models.FloatField()),
                ('artistic_score', models.FloatField()),
                ('total_score', models.FloatField()),
                ('competition', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='figure_skating_game.competition')),
                ('program', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='figure_skating_game.program')),
                ('skater', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='figure_skating_game.skater')),
            ],
        ),
        migrations.AddField(
            model_name='competition',
            name='skaters',
            field=models.ManyToManyField(to='figure_skating_game.skater'),
        ),
    ]
