# Generated by Django 4.2.18 on 2025-04-15 20:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('figure_skating_game', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Element',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('code', models.CharField(max_length=10, unique=True)),
                ('element_type', models.CharField(choices=[('JUMP', 'Jump'), ('SPIN', 'Spin'), ('STEP', 'Step Sequence'), ('CHOREO', 'Choreographic')], max_length=10)),
                ('base_value', models.DecimalField(decimal_places=2, max_digits=5)),
            ],
        ),
        migrations.CreateModel(
            name='ElementProbability',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('success_rate', models.FloatField()),
                ('element', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='figure_skating_game.element')),
            ],
        ),
        migrations.CreateModel(
            name='ExecutedElement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField()),
                ('goe', models.DecimalField(decimal_places=2, max_digits=4)),
                ('element', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='figure_skating_game.element')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='ExecutedProgram',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_score', models.DecimalField(decimal_places=2, max_digits=6)),
            ],
            options={
                'ordering': ['-total_score'],
            },
        ),
        migrations.CreateModel(
            name='ProgramElementOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField()),
                ('element', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='figure_skating_game.element')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.RemoveField(
            model_name='competition',
            name='results',
        ),
        migrations.RemoveField(
            model_name='program',
            name='GOE_list',
        ),
        migrations.RemoveField(
            model_name='program',
            name='duration',
        ),
        migrations.RemoveField(
            model_name='program',
            name='jump_list',
        ),
        migrations.RemoveField(
            model_name='program',
            name='spin_list',
        ),
        migrations.RemoveField(
            model_name='program',
            name='total_score',
        ),
        migrations.RemoveField(
            model_name='skater',
            name='GOE_scores',
        ),
        migrations.RemoveField(
            model_name='skater',
            name='current_program',
        ),
        migrations.RemoveField(
            model_name='skater',
            name='jump_probabilities',
        ),
        migrations.RemoveField(
            model_name='skater',
            name='name',
        ),
        migrations.RemoveField(
            model_name='skater',
            name='past_programs',
        ),
        migrations.RemoveField(
            model_name='skater',
            name='specialty',
        ),
        migrations.AddField(
            model_name='skater',
            name='first_name',
            field=models.CharField(default='temp', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='skater',
            name='hometown',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='skater',
            name='last_name',
            field=models.CharField(default='temp', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='skater',
            name='skating_club',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='competition',
            name='date',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='competition',
            name='skaters',
            field=models.ManyToManyField(related_name='competitions', to='figure_skating_game.skater'),
        ),
        migrations.AlterField(
            model_name='program',
            name='preset',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='program',
            name='skater',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='programs', to='figure_skating_game.skater'),
        ),
        migrations.AlterField(
            model_name='skater',
            name='image',
            field=models.ImageField(upload_to='skater_images/'),
        ),
        migrations.AlterField(
            model_name='skater',
            name='nationality',
            field=models.CharField(max_length=100),
        ),
        migrations.DeleteModel(
            name='JudgingPanel',
        ),
        migrations.AddField(
            model_name='programelementorder',
            name='program',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='figure_skating_game.program'),
        ),
        migrations.AddField(
            model_name='executedprogram',
            name='competition',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='executed_programs', to='figure_skating_game.competition'),
        ),
        migrations.AddField(
            model_name='executedprogram',
            name='program',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='executions', to='figure_skating_game.program'),
        ),
        migrations.AddField(
            model_name='executedelement',
            name='executed_program',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='executed_elements', to='figure_skating_game.executedprogram'),
        ),
        migrations.AddField(
            model_name='elementprobability',
            name='skater',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='element_probs', to='figure_skating_game.skater'),
        ),
        migrations.AddField(
            model_name='program',
            name='elements',
            field=models.ManyToManyField(through='figure_skating_game.ProgramElementOrder', to='figure_skating_game.element'),
        ),
        migrations.AlterUniqueTogether(
            name='programelementorder',
            unique_together={('program', 'order')},
        ),
        migrations.AlterUniqueTogether(
            name='elementprobability',
            unique_together={('skater', 'element')},
        ),
    ]
