# Generated by Django 4.2.18 on 2025-04-16 23:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('figure_skating_game', '0002_element_elementprobability_executedelement_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ElementProbability',
            new_name='ElementProbabilityForSkater',
        ),
    ]
