# Generated by Django 4.2.18 on 2025-04-16 23:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('figure_skating_game', '0003_rename_elementprobability_elementprobabilityforskater'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ElementProbabilityForSkater',
            new_name='ElementProbability',
        ),
    ]
