# Generated by Django 4.2.18 on 2025-04-28 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('figure_skating_game', '0004_rename_elementprobabilityforskater_elementprobability'),
    ]

    operations = [
        migrations.AddField(
            model_name='executedprogram',
            name='placement',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
