# Generated by Django 4.2.18 on 2025-04-28 18:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('figure_skating_game', '0005_executedprogram_placement'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='executedprogram',
            name='placement',
        ),
    ]
