# Generated by Django 4.2.18 on 2025-05-01 14:42

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('figure_skating_game', '0006_remove_executedprogram_placement'),
    ]

    operations = [
        migrations.AlterField(
            model_name='competition',
            name='date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
